### ISSUE TITLE
Draft Project Plan

### ISSUE THREAD

**Issue by shawnkoh** [AY1920S1-CS2103-T11-3/main#12]
## Overview
Team lead: @HoWeiChin 
Documentation: @belbel98   (supported by @shawnkoh )
Testing: everyone
Code quality: @shawnkoh @ooimingsheng 
Integration: @ooimingsheng 
Deliverables and deadlines: @HoWeiChin  
Scheduling and tracking: @HoWeiChin 
Git expert: @ooimingsheng  @shawnkoh 
Intellij expert @belbel98  @HoWeiChin 

General component responsibility
1. Leaderboard @ooimingsheng 
2. Competitors @HoWeiChin 
3. Competitions @shawnkoh  
4. Participation @belbel98 

High level architecture goals
Parsing: AB3 but with support for contexts e.g. creating competition, in-competition & etc
Storage: AB3
UI: JavaFX :(
Event propogation; Consider using google's eventbus or just stick to AB3.

Git strategy
- [x] Adopt branching workflow.
- [x] Always squash and merge PRs
- [x] Generally speaking, either @shawnkoh and @ooimingsheng will approve PRs. they will be merged by author. However, if a PR is made that affects someone else's part - he will be the approver.
- [x] @shawnkoh PRs will be approved by @ooimingsheng and vice versa

## Deliverables
- [ ] Plan out the features required
- [ ] Complete backend CLI
- [ ] Develop GUI `after backend CLI` to minimise the pain of javafx
