### ISSUE TITLE
Competitions

### ISSUE THREAD

**Issue by shawnkoh** [AY1920S1-CS2103-T11-3/main#14]
v1.2
- [ ] Organiser should be able to create a new competition
- [ ] Organiser should be able to view a competition

v1.3
- [ ] Organiser should be able to UD competitions

v...
- [ ] CRUD competitions GUI
